// Static/mock events for use in Events.js and EventDetails.js
export const staticEvents = [
  {
    id: 'static-1',
    slug: 'security-eagles-launch',
    title: 'Security Eagles Launch',
    description: 'Kickoff event for the Security Eagles community. Meet the founders, learn about our mission, and get a sneak peek at upcoming labs and features.',
    start_time: '2024-07-01T18:00:00Z',
    duration_hours: 2,
    location: 'Online',
    attendee_count: 150,
    max_attendees: 500,
    category: { slug: 'webinar', name: 'Webinar' },
    priority: 'normal',
    views: 1200,
    spots_remaining: 350,
    is_physical: false,
    registration_open: true,
    tags: ['community', 'launch'],
    organizer: 'Security Eagles',
    contact_email: 'info@securityeagles.com',
    contact_phone: '123-456-7890',
    agenda: [
      { time: '18:00', title: 'Welcome', description: 'Introduction to Security Eagles' },
      { time: '18:30', title: 'Mission & Vision', description: 'Our goals and plans' },
    ],
    learning_objectives: ['Meet the team', 'Understand the mission'],
    prerequisites: ['Interest in cybersecurity'],
  },
  {
    id: 'static-2',
    slug: 'cloud-security-bootcamp',
    title: 'Cloud Security Bootcamp',
    description: 'A hands-on bootcamp covering cloud security best practices, IAM, and real-world attack simulations.',
    start_time: '2024-07-15T15:00:00Z',
    duration_hours: 3,
    location: 'Security Eagles HQ',
    attendee_count: 80,
    max_attendees: 100,
    category: { slug: 'workshop', name: 'Workshop' },
    priority: 'high',
    views: 800,
    spots_remaining: 20,
    is_physical: true,
    registration_open: true,
    tags: ['training', 'security'],
    organizer: 'Security Eagles',
    contact_email: 'info@securityeagles.com',
    contact_phone: '123-456-7890',
    agenda: [
      { time: '15:00', title: 'Introduction', description: 'Overview of cloud security' },
      { time: '15:30', title: 'IAM and Access Management', description: 'Understanding and implementing IAM' },
      { time: '16:00', title: 'Attack Simulations', description: 'Practical exercises in cloud security' },
      { time: '16:30', title: 'Hands-on Workshop', description: 'Implementing security measures' },
    ],
    learning_objectives: ['Understand cloud security best practices', 'Implement IAM and access management', 'Perform attack simulations'],
    prerequisites: ['Basic understanding of cloud platforms', 'Interest in cybersecurity'],
  },
  {
    id: 'static-3',
    slug: 'capture-the-flag-ctf-challenge',
    title: 'Capture The Flag (CTF) Challenge',
    description: 'Test your skills in our first CTF event! Open to all skill levels, with prizes for top teams.',
    start_time: '2024-08-05T10:00:00Z',
    duration_hours: 4,
    location: 'Online',
    attendee_count: 200,
    max_attendees: 300,
    category: { slug: 'competition', name: 'Competition' },
    priority: 'normal',
    views: 1500,
    spots_remaining: 100,
    is_physical: false,
    registration_open: true,
    tags: ['community', 'competition'],
    organizer: 'Security Eagles',
    contact_email: 'info@securityeagles.com',
    contact_phone: '123-456-7890',
    learning_objectives: ['Understand CTF competitions', 'Practice cybersecurity skills', 'Teamwork and problem-solving'],
    prerequisites: ['Basic understanding of cybersecurity', 'Interest in competitive events'],
  },
]; 